hooks:
  before:npm:release:
    - npm run build:dist
    - ts-node -T bin/prepublish.ts

git:
  commitMessage: "chore(release): ${version} [no ci]"

npm:
  publishPath: ./dist

github:
  release: true

plugins:
  "@release-it/conventional-changelog":
    preset: angular
    infile: CHANGELOG.md
    header: "# Changelog"
