name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v5

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16, 18]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    services:
      rabbitmq:
        image: heidiks/rabbitmq-delayed-message-exchange
        ports:
          - 5672:5672
        options:
          --health-cmd "rabbitmq-diagnostics -q check_virtual_hosts"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          node --version
          npm --version

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Type check
        run: npm run typecheck

      - name: Dry run of publishing
        run: npm run publish:dev:dry

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run coverage

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '18.')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
