name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lints Pull Request commits
        uses: wagoid/commitlint-github-action@v1

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [14, 16]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install --progress=false --loglevel=warn --ignore-scripts

      - name: Type check
        run: npm run typecheck

      - name: Dry run of publishing
        run: npm run publish:dev:dry

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run coverage

      - name: Run Coveralls
        uses: coverallsapp/github-action@master
        if: startsWith(matrix.node-version, '16.')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
