name: release

on:
  workflow_run:
    workflows: [ci]
    branches: [master]
    types: [completed]

  workflow_dispatch:
    inputs:
      releaseItOptions:
        description: release-it options
        required: false
        default: ""
        type: string

jobs:
  release:
    # double check
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://registry.npmjs.org"

      - name: Create and push git tag, publish version to npm and create github release
        run: |
          npm ci --progress=false --loglevel=warn --ignore-scripts
          npm run release -- ${RELEASE_IT_OPTIONS[@]}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          RELEASE_IT_OPTIONS: ${{ github.event.inputs.releaseItOptions }}
